In [2]:
import pandas as pd
import numpy as np

In [3]:
movies = pd.read_csv("C:\\Users\\ADMIN\\Downloads\\movie_rec_dataset\\movies_metadata.csv", low_memory=False)
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
movies = movies[['id', 'title', 'genres', 'overview']]
movies.head()

,id,title,genres,overview
0,862,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ..."
1,8844,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...
2,15602,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...

In [5]:
movies = movies[movies['id'].str.isnumeric()]
movies['id'] = movies['id'].astype(int)

In [6]:
credits = pd.read_csv("C:\\Users\\ADMIN\\Downloads\\movie_rec_dataset\\credits.csv")
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [7]:
keywords = pd.read_csv("C:\\Users\\ADMIN\\Downloads\\movie_rec_dataset\\keywords.csv")
keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [8]:
movies = movies.merge(credits, on='id')
movies = movies.merge(keywords, on='id')

In [9]:
movies.head()
movies.shape
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46628 entries, 0 to 46627
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46628 non-null  int32
 1   title     46624 non-null  object
 2   genres    46628 non-null  object
 3   overview  45633 non-null  object
 4   cast      46628 non-null  object
 5   crew      46628 non-null  object
 6   keywords  46628 non-null  object
dtypes: int32(1), object(6)
memory usage: 2.3+ MB

In [10]:
movies['overview'] = movies['overview'].fillna('')
movies['genres'] = movies['genres'].fillna('[]')
movies['keywords'] = movies['keywords'].fillna('[]')
movies['cast'] = movies['cast'].fillna('[]')
movies['crew'] = movies['crew'].fillna('[]')

In [11]:
import ast

def convert(text):
    try:
        return [i['name'] for i in ast.literal_eval(text)]
    except:
        return []

movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [12]:
def convert_cast(text):
    try:
        return [i['name'] for i in ast.literal_eval(text)[:3]]
    except:
        return []

movies['cast'] = movies['cast'].apply(convert_cast)

In [13]:
def fetch_director(text):
    try:
        for i in ast.literal_eval(text):
            if i['job'] == 'Director':
                return [i['name']]
    except:
        return []
    return []

movies['crew'] = movies['crew'].apply(fetch_director)

In [14]:
def collapse(L):
    return [i.replace(" ", "") for i in L]
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)

In [15]:
movies['tags'] = (
    movies['overview'] + ' ' +
    movies['genres'].apply(lambda x: " ".join(x)) + ' ' +
    movies['keywords'].apply(lambda x: " ".join(x)) + ' ' +
    movies['cast'].apply(lambda x: " ".join(x)) + ' ' +
    movies['crew'].apply(lambda x: " ".join(x))
)

In [16]:
movies['tags'] = movies['tags'].str.lower()

In [17]:
import sys
!"{sys.executable}" -m pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\admin\appdata\roaming\python\python312\site-packages (3.9.4)
Requirement already satisfied: click in c:\users\admin\appdata\roaming\python\python312\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\admin\appdata\roaming\python\python312\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\admin\appdata\roaming\python\python312\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: tqdm in c:\users\admin\appdata\roaming\python\python312\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
import nltk
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

def stem(text):
    return " ".join([ps.stem(word) for word in text.split()])

movies['tags'] = movies['tags'].apply(stem)

In [19]:
!pip install sentence-transformers

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sentence-transformers in c:\users\admin\appdata\roaming\python\python312\site-packages (5.4.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from sentence-transformers) (5.5.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from sentence-transformers) (1.10.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from sentence-transformers) (2.11.0)
Requirement already satisfied: numpy>=1.20.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from sentence-transformers) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\admin\appdata\roaming\python\python312\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\users\admin\appdata\roaming\python\python312\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in c:\users\admin\appdata\roaming\python\python312\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in c:\users\admin\appdata\roaming\python\python312\site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\admin\appdata\roaming\python\python312\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: regex>=2025.10.22 in c:\users\admin\appdata\roaming\python\python312\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\admin\appdata\roaming\python\python312\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.11.0)
Requirement already satisfied: certifi in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2025.10.5)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.19.2)
Requirement already satisfied: sniffio>=1.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

movies = movies.drop_duplicates(subset='title')
movies.reset_index(drop=True, inplace=True)

tfidf = TfidfVectorizer(max_features=5000,stop_words='english')
tfidf_vectors = tfidf.fit_transform(movies['tags']).toarray()  # sparse matrix

from sentence_transformers import SentenceTransformer

semantic_model = SentenceTransformer('all-MiniLM-L6-v2')

semantic_vectors = semantic_model.encode(
    movies['tags'].tolist(),
    show_progress_bar=True
)

C:\Users\ADMIN\AppData\Roaming\Python\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|█████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 2339.44it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|█████████████████████████████████████████████████████████████████████| 1322/1322 [19:10<00:00,  1.15it/s]

In [24]:
def get_recommendations(movie_title, tfidf_vectors, semantic_vectors, movies_df, top_n=10):

    titles = movies_df['title'].fillna('').str.lower()

    # Exact match first
    matches = movies_df[titles == movie_title.lower()]

    # Fallback partial match
    if matches.empty:
        matches = movies_df[titles.str.contains(movie_title.lower(), na=False)]

    if matches.empty:
        return "Movie not found"

    idx = matches.index[0]

    from sklearn.metrics.pairwise import cosine_similarity

    tfidf_scores = cosine_similarity(
        tfidf_vectors[idx].reshape(1, -1),
        tfidf_vectors
    ).flatten()

    semantic_scores = cosine_similarity(
        semantic_vectors[idx].reshape(1, -1),
        semantic_vectors
    ).flatten()

    final_scores = (0.5 * tfidf_scores) + (0.5 * semantic_scores)

    similar_movies = sorted(
        list(enumerate(final_scores)),
        key=lambda x: x[1],
        reverse=True
    )

    seen_titles = set()
    recommendations = []

    for i, score in similar_movies:
        title = movies_df.iloc[i].title

        if title.lower() != movie_title.lower() and title.lower() not in seen_titles:
            seen_titles.add(title.lower())
            recommendations.append(title)

        if len(recommendations) == top_n:
            break

    return recommendations

In [25]:
get_recommendations("shark", tfidf_vectors, semantic_vectors, movies)

['Swimming with Sharks',
 'Stand-In',
 'Dancing in September',
 'What Just Happened',
 'Star Spangled Rhythm',
 'The Player',
 'Bowfinger',
 'Hollywood Story',
 'Man About Town',
 'In the Soup']

In [26]:
import pickle
pickle.dump(tfidf_vectors, open('tfidf_vectors.pkl', 'wb'))
pickle.dump(semantic_vectors, open('semantic_vectors.pkl', 'wb'))
pickle.dump(movies, open('movies.pkl', 'wb'))

In [36]:
import os
print(os.getcwd())

C:\Users\ADMIN

In [35]:
movies_loaded = pickle.load(open('movies.pkl', 'rb'))
tfdif_vectors_loaded = pickle.load(open('tfidf_vectors.pkl', 'rb'))
semantic_vectors_loaded = pickle.load(open('semantic_vectors.pkl', 'rb'))
print(movies_loaded.shape)
print(tfdif_vectors_loaded.shape)
print(semantic_vectors_loaded.shape)

(42277, 8)
(42277, 10000)
(42277, 384)

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pickle

tfidf = TfidfVectorizer(max_features=5000,stop_words='english')
tfidf_vectors = tfidf.fit_transform(movies['tags']).toarray()  # sparse matrix

pickle.dump(tfidf_vectors, open('tfidf_vectors.pkl', 'wb'))

NameError: name 'movies' is not defined